name: abl_resistance
channels:
  - conda-forge
  - omnia
  - openeye
  - rdkit
dependencies:
  - pip
  - python=3.7
  - appdirs
  - jupyterlab
  - mdanalysis
  - rdkit
  - openeye-toolkits
  - openforcefield
  - pip:
      - https://github.com/volkamerlab/klifs_utils/archive/master.tar.gz
      - git+git://github.com/openkinome/kinoml.git@8de41d87a3b675b6fd8157d37d2e0a3f0f38a616
